### ISSUE TITLE
Improvement suggestion: Change of MQTT topic

### ISSUE THREAD

**Issue by HakamSaffour** [mruettgers/SMLReader#6] opened 2020-09-23 07:45 UTC
Scenario 1: After setting up everything and getting some results, I wanted to change the MQTT topic, I entered the local IP address of the SMLReader, then I changed the MQTT topic , then I clicked on 'Save'

Result: the SMLReader can not connect to the MQTT broker

Scenario 2: did the same as in scenario 1 and I also retyped the MQTT password, then clicked 'Save'
Result: the SMLReader do connect to the MQTT broker

![image](https://user-images.githubusercontent.com/11553465/93981867-cd495d80-fd80-11ea-8c71-4351b22d187e.png)

Potential improvement: make sure that MQTT password is not lost by changing the configuration

**Comment by mruettgers** [comment] 2020-09-24 20:05
Hey @HakamSaffour,

thank you for your feedback.
I'll have a look at as soon as possible, but I guess this is an issue with the third-party-library [IotWebConf](https://github.com/prampec/IotWebConf).

Michael

**Comment by mruettgers** [comment] 2021-04-23 19:39
I'm closing this issue for now, as I don't currently have time to debug the third-party library. I admit that the problem is annoying, but it can be fixed with a workaround and only occurs during the initial setup.

**Closed by mruettgers** 2021-04-23 19:39 UTC
Labels: bug
